import TitlePage from '@/components/TitlePage'
import { Inter } from 'next/font/google'
import './global.css'

export const metadata = {
  title: 'Ohlala - Estudio de belleza',
  description: 'Generated by Next.js'
}

const inter = Inter({
  weight: ['300', '400', '700'],
  style: ['normal'],
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <TitlePage />
        <div className='content-post'>
        {children}
        </div>
      </body>
    </html>
  )
}
